
GLOBAL_COLORS = {
	"alpha grey"		 		: "COLOR_ALPHA_GREY",
	"white" 					: "COLOR_WHITE",
	"black"				 		: "COLOR_BLACK",
	"dark grey" 				: "COLOR_DARK_GREY",
	"grey" 						: "COLOR_GREY",
	"light grey"		 		: "COLOR_LIGHT_GREY",
	"red" 						: "COLOR_RED",
	"green"				 		: "COLOR_GREEN",
	"blue" 						: "COLOR_BLUE",
	"cyan" 						: "COLOR_CYAN",
	"yellow"	 				: "COLOR_YELLOW",
	"magenta" 					: "COLOR_MAGENTA",
	"yield food" 				: "COLOR_YIELD_FOOD",
	"yield production" 			: "COLOR_YIELD_PRODUCTION",
	"yield commerce" 			: "COLOR_YIELD_COMMERCE",
	"city blue" 				: "COLOR_CITY_BLUE",
	"city grey" 				: "COLOR_CITY_GREY",
	"city brown" 				: "COLOR_CITY_BROWN",
	"city green" 				: "COLOR_CITY_GREEN",
	"font red" 					: "COLOR_FONT_RED",
	"font green" 				: "COLOR_FONT_GREEN",
	"research stored" 			: "COLOR_RESEARCH_STORED",
	"research rate" 			: "COLOR_RESEARCH_RATE",
	"culture stored" 			: "COLOR_CULTURE_STORED",
	"culture rate" 				: "COLOR_CULTURE_RATE",
	"great people stored" 		: "COLOR_GREAT_PEOPLE_STORED",
	"great people rate" 		: "COLOR_GREAT_PEOPLE_RATE",
	"negative rate" 			: "COLOR_NEGATIVE_RATE",
	"empty" 					: "COLOR_EMPTY",
	"popup text" 				: "COLOR_POPUP_TEXT",
	"popup selected" 			: "COLOR_POPUP_SELECTED",
	"tech text" 				: "COLOR_TECH_TEXT",
	"unit text" 				: "COLOR_UNIT_TEXT",
	"building text" 			: "COLOR_BUILDING_TEXT",
	"project text" 				: "COLOR_PROJECT_TEXT",
	"highlight" 				: "COLOR_HIGHLIGHT_TEXT",
	"alt highlight" 			: "COLOR_ALT_HIGHLIGHT_TEXT",
	"warning text" 				: "COLOR_WARNING_TEXT",
	"positive text" 			: "COLOR_POSITIVE_TEXT",
	"negative text" 			: "COLOR_NEGATIVE_TEXT",
	"brown text" 				: "COLOR_BROWN_TEXT",
	"selected text" 			: "COLOR_SELECTED_TEXT",
	"water text" 				: "COLOR_WATER_TEXT",
	"menu blue" 				: "COLOR_MENU_BLUE",
	"dawn of man text" 			: "COLOR_DAWN_OF_MAN_TEXT",
	"tech green" 				: "COLOR_TECH_GREEN",
	"tech blue" 				: "COLOR_TECH_BLUE",
	"tech working" 				: "COLOR_TECH_WORKING",
	"tech black" 				: "COLOR_TECH_BLACK",
	"tech red" 					: "COLOR_TECH_RED",
	"player black" 				: "COLOR_PLAYER_BLACK",
	"player black text" 		: "COLOR_PLAYER_BLACK_TEXT",
	"player blue" 				: "COLOR_PLAYER_BLUE",
	"player blue text" 			: "COLOR_PLAYER_BLUE_TEXT",
	"player brown" 				: "COLOR_PLAYER_BROWN",
	"player brown text" 		: "COLOR_PLAYER_BROWN_TEXT",
	"player cyan" 				: "COLOR_PLAYER_CYAN",
	"player cyan text" 			: "COLOR_PLAYER_CYAN_TEXT",
	"player dark blue" 			: "COLOR_PLAYER_DARK_BLUE",
	"player dark blue text" 	: "COLOR_PLAYER_DARK_BLUE_TEXT",
	"player dark cyan" 			: "COLOR_PLAYER_DARK_CYAN",
	"player dark cyan text" 	: "COLOR_PLAYER_DARK_CYAN_TEXT",
	"player dark green" 		: "COLOR_PLAYER_DARK_GREEN",
	"player dark green text" 	: "COLOR_PLAYER_DARK_GREEN_TEXT",
	"player dark pink" 			: "COLOR_PLAYER_DARK_PINK",
	"player dark pink text" 	: "COLOR_PLAYER_DARK_PINK_TEXT",
	"player dark purple" 		: "COLOR_PLAYER_DARK_PURPLE",
	"player dark purple text" 	: "COLOR_PLAYER_DARK_PURPLE_TEXT",
	"player dark red" 			: "COLOR_PLAYER_DARK_RED",
	"player dark red text" 		: "COLOR_PLAYER_DARK_RED_TEXT",
	"player dark yellow" 		: "COLOR_PLAYER_DARK_YELLOW",
	"player dark yellow text" 	: "COLOR_PLAYER_DARK_YELLOW_TEXT",
	"player grey" 				: "COLOR_PLAYER_GRAY",
	"player grey text" 			: "COLOR_PLAYER_GRAY_TEXT",
	"player green" 				: "COLOR_PLAYER_GREEN",
	"player green text" 		: "COLOR_PLAYER_GREEN_TEXT",
	"player orange" 			: "COLOR_PLAYER_ORANGE",
	"player orange text" 		: "COLOR_PLAYER_ORANGE_TEXT",
	"player peach" 				: "COLOR_PLAYER_PEACH",
	"player peach text" 		: "COLOR_PLAYER_PEACH_TEXT",
	"player pink" 				: "COLOR_PLAYER_PINK",
	"player pink text" 			: "COLOR_PLAYER_PINK_TEXT",
	"player purple" 			: "COLOR_PLAYER_PURPLE",
	"player purple text" 		: "COLOR_PLAYER_PURPLE_TEXT",
	"player red" 				: "COLOR_PLAYER_RED",
	"player red text" 			: "COLOR_PLAYER_RED_TEXT",
	"player white" 				: "COLOR_PLAYER_WHITE",
	"player white text" 		: "COLOR_PLAYER_WHITE_TEXT",
	"player yellow" 			: "COLOR_PLAYER_YELLOW",
	"player yellow text" 		: "COLOR_PLAYER_YELLOW_TEXT",
}
